FROM apache/superset:latest

USER root
RUN pip install --no-cache-dir psycopg2-binary --target /app/.venv/lib/python3.10/site-packages
COPY superset_config.py /app/pythonpath/superset_config.py

USER superset
